name: "Format and Lint"

on:
  pull_request:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install System Deps
        run: sudo apt update && sudo apt install libc6

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn format-check
