name: "Test"

on:
  pull_request:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test
